--
-- DDL generated by Hibernate 6.6 (Spring Boot 3.5.13)
--

create table card (
    id uuid not null,
    card_number varchar(255) not null,
    card_holder_name varchar(255) not null,
    created_at timestamp(6) not null,
    proposal_id uuid not null,
    primary key (id)
);

create table proposal (
    id uuid not null,
    document varchar(255) unique,
    email varchar(255),
    name varchar(255),
    salary numeric(38,2),
    address varchar(255),
    status varchar(255) check (status in ('ELIGIBLE','NOT_ELIGIBLE','ELIGIBLE_WITH_ATTACHED_CARD')),
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);
