version: '3.1'

services:
  postgres:
    image: "postgres:13.3"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./bootstrap:/docker-entrypoint-initdb.d
  wiremock: # https://www.alexhyett.com/mock-api-calls-wiremock/
    image: "rodolpheche/wiremock"
    ports:
      - 9999:8080
    volumes:
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
    command:
      - -verbose
      - -global-response-templating

volumes:
  database-data: # named volumes can be managed easier using docker-compose