##
# Spring configuration
##
spring.output.ansi.enabled=ALWAYS

##
# DataSource configuration
##
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.sql.init.platform=postgres

##
# JPA/Hibernate configuration
##
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
# batch size
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.jdbc.order_inserts=true
spring.jpa.properties.hibernate.jdbc.order_updates=true

##
# DataSource Proxy
# (https://github.com/gavlyukovskiy/spring-boot-data-source-decorator)
# It allows us to log the SQL statements that are batched by Hibernate batchSize
##
decorator.datasource.datasource-proxy.multiline=true
decorator.datasource.datasource-proxy.query.enable-logging=true
decorator.datasource.datasource-proxy.query.log-level=info

##
# Integrations
##
spring.cloud.openfeign.client.config.default.logger-level=basic

spring.cloud.openfeign.client.config.financialAnalysisClient.url=http://localhost:9999/
spring.cloud.openfeign.client.config.financialAnalysisClient.logger-level=full
logging.level.br.com.deveficiente.nobank.proposals.integration.FinancialAnalysisClient=DEBUG

spring.cloud.openfeign.client.config.cardsClient.url=http://localhost:9999/
spring.cloud.openfeign.client.config.cardsClient.logger-level=basic
logging.level.br.com.deveficiente.nobank.cards.integration.CardsClient=DEBUG