##
# Spring configuration
##
spring:
  output:
    ansi:
      enabled: ALWAYS

  ##
  # DataSource configuration
  ##
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
  sql:
    init:
      platform: postgres

  ##
  # JPA/Hibernate configuration
  ##
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  ##
  # Integrations
  ##
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: basic
          financialAnalysisClient:
            url: http://localhost:9999/
            logger-level: full
          cardsClient:
            url: http://localhost:9999/
            logger-level: basic

##
# Logging
##
logging:
  level:
    br.com.deveficiente.nobank.proposals.integration.FinancialAnalysisClient: DEBUG
    br.com.deveficiente.nobank.cards.integration.CardsClient: DEBUG
